baseURL: "https://www.cybersmith.co.uk/"
title: "Cybersmith"
locale: "en-GB"
disableKinds: ["taxonomy", "RSS"]
enableRobotsTXT: true
disableHugoGeneratorInject: true
sitemap:
    changefreq: monthly
security:
    allowContent: ['.*']
